variables:
  POSTGRES_DB: "api"
  POSTGRES_USER: "api"
  POSTGRES_PASSWORD: "example"
  DEBUG: "newsai-api:*"
  PORT: "4000"
  API_VERSION: "1.0"
  JWT_SECRET: "helloworld"
  UNIQUE_NAME_PG_DB: $POSTGRES_DB
  UNIQUE_NAME_PG_TEST_DB: $POSTGRES_DB
  UNIQUE_NAME_PG_PORT: 5432
  UNIQUE_NAME_PG_HOST: "db"
  UNIQUE_NAME_PG_USER: $POSTGRES_USER
  UNIQUE_NAME_PG_PASSWD: $POSTGRES_PASSWORD
  UNIQUE_NAME_PG_SSL: "false"
  UNIQUE_NAME_PG_CERT_CA: "somethingHere"
  REDIS_URL: "redis://redis/0"

image: node:10.16.3

services:
  - name: postgres:11.5
    alias: db
  - name: redis:5.0.5
    alias: redis

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/
    - .yarn

stages:
  - test

before_script:
  - cp .env.example .env
  # Install yarn as outlined in (https://yarnpkg.com/lang/en/docs/install/#alternatives-stable)
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  # Make available in the current terminal
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
  - yarn install

lint:
  stage: test
  script:
    - yarn install
    - yarn lint

#test:
#  stage: test
#  script:
#    - yarn install
#    - yarn test
